import type { CommentRecord } from "./types";

export const comments: CommentRecord[] = [
  {
    id: "comment-appam-1",
    recipeId: "appam-vegetable-stew",
    author: "Ananya",
    text: "The stew came out creamy and comforting. I added a little extra pepper.",
    createdAt: "2026-08-04T09:30:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-appam-2",
  },
  {
    id: "comment-appam-2",
    recipeId: "appam-vegetable-stew",
    author: "Maya",
    text: "Letting the batter ferment overnight made the appam beautifully soft.",
    createdAt: "2026-08-09T12:15:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-appam-1",
    nextSiblingId: null,
  },
  {
    id: "comment-fish-1",
    recipeId: "kerala-fish-curry",
    author: "Rahul",
    text: "The tamarind gives this curry just the right amount of tang.",
    createdAt: "2026-08-11T16:20:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-fish-2",
  },
  {
    id: "comment-fish-2",
    recipeId: "kerala-fish-curry",
    author: "Leena",
    text: "Even better the next day after the flavors had time to settle.",
    createdAt: "2026-08-12T08:10:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-fish-1",
    nextSiblingId: null,
  },
  {
    id: "comment-biryani-1",
    recipeId: "malabar-chicken-biryani",
    author: "Nikhil",
    text: "The rice stayed fluffy and the spice level was perfect for us.",
    createdAt: "2026-08-14T11:05:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-biryani-2",
  },
  {
    id: "comment-biryani-2",
    recipeId: "malabar-chicken-biryani",
    author: "Sara",
    text: "A lovely weekend recipe. Fried onions on top are worth the extra time.",
    createdAt: "2026-08-18T19:40:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-biryani-1",
    nextSiblingId: null,
  },
  {
    id: "comment-puttu-1",
    recipeId: "puttu-kadala-curry",
    author: "Devika",
    text: "The curry is hearty and the puttu texture was just right.",
    createdAt: "2026-08-20T07:30:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-puttu-2",
  },
  {
    id: "comment-puttu-2",
    recipeId: "puttu-kadala-curry",
    author: "Arun",
    text: "I soaked the chickpeas overnight and the cooking time was spot on.",
    createdAt: "2026-08-21T10:00:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-puttu-1",
    nextSiblingId: null,
  },
  {
    id: "comment-avial-1",
    recipeId: "vegetable-avial",
    author: "Meera",
    text: "A great way to use the vegetables in my fridge. The coconut sauce is lovely.",
    createdAt: "2026-08-23T13:45:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-avial-2",
  },
  {
    id: "comment-avial-2",
    recipeId: "vegetable-avial",
    author: "Ishan",
    text: "I kept the vegetables slightly firm and it turned out beautifully.",
    createdAt: "2026-08-24T18:05:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-avial-1",
    nextSiblingId: null,
  },
  {
    id: "comment-chips-1",
    recipeId: "crispy-banana-chips",
    author: "Kavya",
    text: "Thin slices make all the difference. These disappeared quickly.",
    createdAt: "2026-08-26T14:25:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-chips-2",
  },
  {
    id: "comment-chips-2",
    recipeId: "crispy-banana-chips",
    author: "Thomas",
    text: "A pinch of chili powder is a nice variation for snack time.",
    createdAt: "2026-08-27T15:50:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-chips-1",
    nextSiblingId: null,
  },
  {
    id: "comment-payasam-1",
    recipeId: "palada-payasam",
    author: "Anjali",
    text: "Slow simmering gave it a lovely creamy texture. A new favorite.",
    createdAt: "2026-08-29T17:15:00.000Z",
    parentCommentId: null,
    previousSiblingId: null,
    nextSiblingId: "comment-payasam-2",
  },
  {
    id: "comment-payasam-2",
    recipeId: "palada-payasam",
    author: "Vijay",
    text: "I toasted the cashews in ghee just before serving. Delicious.",
    createdAt: "2026-08-30T20:30:00.000Z",
    parentCommentId: null,
    previousSiblingId: "comment-payasam-1",
    nextSiblingId: null,
  },
];