import { IngredientUnit, type Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    id: "appam-vegetable-stew",
    imageUrl: "/images/recipes/appam-vegetable-stew.jpg",
    videoUrl: "/videos/recipes/appam-vegetable-stew.mp4",
    title: "Appam with Vegetable Stew",
    description: "Lacy fermented rice pancakes served with vegetables simmered in coconut milk.",
    ingredients: [
      { name: "raw rice", amount: 2, units: IngredientUnit.Cup },
      { name: "grated coconut", amount: 1, units: IngredientUnit.Cup },
      { name: "mixed vegetables", amount: 350, units: IngredientUnit.Gram },
      { name: "coconut milk", amount: 400, units: IngredientUnit.Milliliter },
      { name: "green chili", amount: 2, units: IngredientUnit.Piece },
      { name: "curry leaves", amount: 1, units: IngredientUnit.Pinch },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Soak the rice, blend it with coconut and water, then leave the batter to ferment overnight." },
      { stepNumber: 2, description: "Simmer the mixed vegetables with chilies and curry leaves until just tender." },
      { stepNumber: 3, description: "Stir in the coconut milk and warm the stew gently without boiling." },
      { stepNumber: 4, description: "Pour a ladle of batter into a hot appam pan, swirl, cover, and cook until the edges are crisp." },
    ],
    rating: 4.8,
    comments: { collection: "comments", headId: "comment-appam-1", tailId: "comment-appam-2" },
  },
  {
    id: "kerala-fish-curry",
    imageUrl: "/images/recipes/kerala-fish-curry.jpg",
    videoUrl: "/videos/recipes/kerala-fish-curry.mp4",
    title: "Kerala Fish Curry",
    description: "A tangy red curry with tamarind, ginger, and fragrant curry leaves.",
    ingredients: [
      { name: "firm white fish", amount: 600, units: IngredientUnit.Gram },
      { name: "shallots", amount: 8, units: IngredientUnit.Piece },
      { name: "chili powder", amount: 2, units: IngredientUnit.Tablespoon },
      { name: "tamarind", amount: 25, units: IngredientUnit.Gram },
      { name: "ginger", amount: 20, units: IngredientUnit.Gram },
      { name: "coconut oil", amount: 2, units: IngredientUnit.Tablespoon },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Soak the tamarind in warm water and strain to make a tangy extract." },
      { stepNumber: 2, description: "Heat coconut oil in a clay pot and soften the shallots, ginger, and curry leaves." },
      { stepNumber: 3, description: "Add chili powder and tamarind extract, then simmer the curry base for several minutes." },
      { stepNumber: 4, description: "Slide in the fish and cook gently until flaky and infused with the sauce." },
    ],
    rating: 4.7,
    comments: { collection: "comments", headId: "comment-fish-1", tailId: "comment-fish-2" },
  },
  {
    id: "malabar-chicken-biryani",
    imageUrl: "/images/recipes/malabar-chicken-biryani.jpg",
    videoUrl: "/videos/recipes/malabar-chicken-biryani.mp4",
    title: "Malabar Chicken Biryani",
    description: "Fragrant short-grain rice layered with spiced chicken and crisp onions.",
    ingredients: [
      { name: "kaima rice", amount: 500, units: IngredientUnit.Gram },
      { name: "chicken", amount: 750, units: IngredientUnit.Gram },
      { name: "onions", amount: 3, units: IngredientUnit.Piece },
      { name: "plain yogurt", amount: 150, units: IngredientUnit.Milliliter },
      { name: "garlic cloves", amount: 5, units: IngredientUnit.Clove },
      { name: "ghee", amount: 3, units: IngredientUnit.Tablespoon },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Marinate the chicken with yogurt, garlic, and the biryani spices." },
      { stepNumber: 2, description: "Cook the kaima rice until almost tender, then drain and set aside." },
      { stepNumber: 3, description: "Brown the onions in ghee, add the marinated chicken, and cook until nearly done." },
      { stepNumber: 4, description: "Layer the rice over the chicken, cover tightly, and steam on low heat until cooked through." },
    ],
    rating: 4.9,
    comments: { collection: "comments", headId: "comment-biryani-1", tailId: "comment-biryani-2" },
  },
  {
    id: "puttu-kadala-curry",
    imageUrl: "/images/recipes/puttu-kadala-curry.jpg",
    videoUrl: "/videos/recipes/puttu-kadala-curry.mp4",
    title: "Puttu and Kadala Curry",
    description: "Steamed rice flour and coconut paired with peppery black chickpea curry.",
    ingredients: [
      { name: "roasted rice flour", amount: 2, units: IngredientUnit.Cup },
      { name: "grated coconut", amount: 1, units: IngredientUnit.Cup },
      { name: "black chickpeas", amount: 250, units: IngredientUnit.Gram },
      { name: "onion", amount: 1, units: IngredientUnit.Piece },
      { name: "coriander powder", amount: 2, units: IngredientUnit.Teaspoon },
      { name: "water", amount: 500, units: IngredientUnit.Milliliter },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Soak the black chickpeas overnight, then pressure-cook until tender." },
      { stepNumber: 2, description: "Moisten the rice flour with salted water until it holds together when pressed but remains crumbly." },
      { stepNumber: 3, description: "Layer the rice flour and grated coconut in a puttu steamer and steam until fragrant." },
      { stepNumber: 4, description: "Simmer the cooked chickpeas with onion and coriander spices, then serve with the warm puttu." },
    ],
    rating: 4.6,
    comments: { collection: "comments", headId: "comment-puttu-1", tailId: "comment-puttu-2" },
  },
  {
    id: "vegetable-avial",
    imageUrl: "/images/recipes/vegetable-avial.jpg",
    videoUrl: "/videos/recipes/vegetable-avial.mp4",
    title: "Garden Vegetable Avial",
    description: "Seasonal vegetables coated in a gently spiced coconut and yogurt sauce.",
    ingredients: [
      { name: "mixed vegetables", amount: 500, units: IngredientUnit.Gram },
      { name: "grated coconut", amount: 0.75, units: IngredientUnit.Cup },
      { name: "plain yogurt", amount: 120, units: IngredientUnit.Milliliter },
      { name: "cumin seeds", amount: 1, units: IngredientUnit.Teaspoon },
      { name: "green chilies", amount: 2, units: IngredientUnit.Piece },
      { name: "coconut oil", amount: 1, units: IngredientUnit.Tablespoon },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Cut the vegetables into even batons and cook them with a splash of water until tender-crisp." },
      { stepNumber: 2, description: "Grind the coconut, cumin, and green chilies into a coarse paste." },
      { stepNumber: 3, description: "Fold the coconut paste through the vegetables and simmer briefly." },
      { stepNumber: 4, description: "Turn off the heat, stir in the yogurt, and finish with coconut oil." },
    ],
    rating: 4.5,
    comments: { collection: "comments", headId: "comment-avial-1", tailId: "comment-avial-2" },
  },
  {
    id: "crispy-banana-chips",
    imageUrl: "/images/recipes/crispy-banana-chips.jpg",
    videoUrl: "/videos/recipes/crispy-banana-chips.mp4",
    title: "Crispy Banana Chips",
    description: "Thin raw banana slices fried until crisp and finished with a touch of salt.",
    ingredients: [
      { name: "raw bananas", amount: 4, units: IngredientUnit.Piece },
      { name: "coconut oil", amount: 750, units: IngredientUnit.Milliliter },
      { name: "turmeric powder", amount: 0.5, units: IngredientUnit.Teaspoon },
      { name: "salt", amount: 1, units: IngredientUnit.Teaspoon },
      { name: "water", amount: 2, units: IngredientUnit.Tablespoon },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Peel the raw bananas and slice them very thinly and evenly." },
      { stepNumber: 2, description: "Dissolve the turmeric and salt in water, then lightly coat the banana slices." },
      { stepNumber: 3, description: "Fry small batches in hot coconut oil until crisp and lightly golden." },
      { stepNumber: 4, description: "Drain thoroughly and let the chips cool completely before serving." },
    ],
    rating: 4.4,
    comments: { collection: "comments", headId: "comment-chips-1", tailId: "comment-chips-2" },
  },
  {
    id: "palada-payasam",
    imageUrl: "/images/recipes/palada-payasam.jpg",
    videoUrl: "/videos/recipes/palada-payasam.mp4",
    title: "Palada Payasam",
    description: "A slow-simmered milk pudding with rice ada, cardamom, and golden cashews.",
    ingredients: [
      { name: "rice ada", amount: 100, units: IngredientUnit.Gram },
      { name: "milk", amount: 1, units: IngredientUnit.Liter },
      { name: "sugar", amount: 150, units: IngredientUnit.Gram },
      { name: "ghee", amount: 2, units: IngredientUnit.Tablespoon },
      { name: "cashews", amount: 30, units: IngredientUnit.Gram },
      { name: "cardamom powder", amount: 1, units: IngredientUnit.Pinch },
    ],
    cookingSteps: [
      { stepNumber: 1, description: "Rinse the rice ada and cook it briefly in boiling water, then drain." },
      { stepNumber: 2, description: "Bring the milk to a gentle simmer in a heavy-bottomed pan." },
      { stepNumber: 3, description: "Add the ada and sugar, stirring often as the milk reduces and thickens." },
      { stepNumber: 4, description: "Fry the cashews in ghee, stir them into the payasam, and finish with cardamom." },
    ],
    rating: 4.9,
    comments: { collection: "comments", headId: "comment-payasam-1", tailId: "comment-payasam-2" },
  },
];